/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => VectrolaSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var GOOGLE_CLIENT_ID = "212647824656-9h9gchm0msibletsog338miabe9qtbe1.apps.googleusercontent.com";
var OAUTH_SERVER = "https://vectrola-oauth.up.railway.app";
var REDIRECT_URI = `${OAUTH_SERVER}/callback`;
var SCOPES = "https://www.googleapis.com/auth/drive.readonly https://www.googleapis.com/auth/drive.file";
var DEFAULT_SETTINGS = {
  accessToken: "",
  refreshToken: "",
  tokenExpiry: 0,
  userEmail: "",
  driveFolderPath: "/Vectrola/wiki",
  autoSyncOnOpen: true,
  syncIntervalMinutes: 5,
  lastSyncTime: 0,
  syncCache: {}
};
function generateCodeVerifier() {
  const array = new Uint8Array(32);
  crypto.getRandomValues(array);
  return base64UrlEncode(array);
}
async function generateCodeChallenge(verifier) {
  const encoder = new TextEncoder();
  const data = encoder.encode(verifier);
  const digest = await crypto.subtle.digest("SHA-256", data);
  return base64UrlEncode(new Uint8Array(digest));
}
function generateRandomState() {
  const array = new Uint8Array(16);
  crypto.getRandomValues(array);
  return base64UrlEncode(array);
}
function base64UrlEncode(buffer) {
  let binary = "";
  for (let i = 0; i < buffer.length; i++) {
    binary += String.fromCharCode(buffer[i]);
  }
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}
var VectrolaSyncPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.syncInterval = null;
    // =========================================================================
    // Sync Operations
    // =========================================================================
    this.syncStats = { processed: 0, downloaded: 0, skipped: 0, total: 0 };
    this.syncCancelled = false;
    this.isSyncing = false;
    this.currentNotice = null;
    this.noticeContent = null;
  }
  async onload() {
    await this.loadSettings();
    this.api = {
      fetchDriveFile: this.fetchDriveFile.bind(this),
      isAuthenticated: this.isAuthenticated.bind(this)
    };
    this.addRibbonIcon("refresh-cw", "Sync with Vectrola", async () => {
      await this.syncFromDrive();
    });
    this.addCommand({
      id: "vectrola-sync-pull",
      name: "Pull wiki from Google Drive",
      callback: async () => {
        await this.syncFromDrive();
      }
    });
    this.addCommand({
      id: "vectrola-sync-push",
      name: "Push wiki to Google Drive",
      callback: async () => {
        await this.syncToDrive();
      }
    });
    this.addCommand({
      id: "vectrola-auth",
      name: "Sign in with Google Drive",
      callback: async () => {
        await this.authenticate();
      }
    });
    this.addCommand({
      id: "vectrola-signout",
      name: "Sign out from Google Drive",
      callback: async () => {
        await this.signOut();
      }
    });
    this.addSettingTab(new VectrolaSyncSettingTab(this.app, this));
    if (this.settings.autoSyncOnOpen && this.isAuthenticated()) {
      setTimeout(() => this.syncFromDrive(), 3e3);
    }
    this.setupSyncInterval();
  }
  onunload() {
    if (this.syncInterval) {
      window.clearInterval(this.syncInterval);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  setupSyncInterval() {
    if (this.syncInterval) {
      window.clearInterval(this.syncInterval);
    }
    if (this.settings.syncIntervalMinutes > 0 && this.isAuthenticated()) {
      this.syncInterval = window.setInterval(
        () => this.syncFromDrive(),
        this.settings.syncIntervalMinutes * 60 * 1e3
      );
    }
  }
  isAuthenticated() {
    return !!(this.settings.accessToken && this.settings.refreshToken);
  }
  // =========================================================================
  // OAuth Authentication (Server-side token exchange)
  // =========================================================================
  async authenticate() {
    const codeVerifier = generateCodeVerifier();
    const codeChallenge = await generateCodeChallenge(codeVerifier);
    const state = generateRandomState();
    try {
      await (0, import_obsidian.requestUrl)({
        url: `${OAUTH_SERVER}/auth/start`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ state, code_verifier: codeVerifier })
      });
    } catch (error) {
      console.error("Failed to start auth session:", error);
      new import_obsidian.Notice("Failed to connect to auth server. Please try again.");
      return;
    }
    let authUrl = `https://accounts.google.com/o/oauth2/v2/auth?client_id=${encodeURIComponent(GOOGLE_CLIENT_ID)}&redirect_uri=${encodeURIComponent(REDIRECT_URI)}&response_type=code&scope=${encodeURIComponent(SCOPES)}&access_type=offline&prompt=consent&code_challenge=${codeChallenge}&code_challenge_method=S256&state=${state}`;
    if (this.settings.userEmail) {
      authUrl += `&login_hint=${encodeURIComponent(this.settings.userEmail)}`;
    }
    try {
      const { shell } = require("electron");
      shell.openExternal(authUrl);
    } catch (e) {
      window.open(authUrl);
    }
    const code = await this.promptForAuthCode();
    if (!code) {
      new import_obsidian.Notice("Authentication cancelled.");
      return;
    }
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: `${OAUTH_SERVER}/auth/token`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ code, state })
      });
      const tokens = response.json;
      if (tokens.error) {
        throw new Error(tokens.error);
      }
      this.settings.accessToken = tokens.access_token;
      this.settings.refreshToken = tokens.refresh_token || this.settings.refreshToken;
      this.settings.tokenExpiry = Date.now() + tokens.expires_in * 1e3;
      try {
        const userInfo = await this.getUserInfo(tokens.access_token);
        if (userInfo.email) {
          this.settings.userEmail = userInfo.email;
        }
      } catch (e) {
      }
      await this.saveSettings();
      new import_obsidian.Notice("\u2705 Successfully connected to Google Drive!");
      this.setupSyncInterval();
    } catch (error) {
      console.error("Token exchange failed:", error);
      new import_obsidian.Notice(`Authentication failed: ${error.message || "Please try again."}`);
    }
  }
  async promptForAuthCode() {
    return new Promise((resolve) => {
      const modal = new AuthCodeModal(this.app, (code) => {
        resolve(code);
      });
      modal.open();
    });
  }
  async getUserInfo(accessToken) {
    const response = await (0, import_obsidian.requestUrl)({
      url: "https://www.googleapis.com/oauth2/v2/userinfo",
      method: "GET",
      headers: {
        Authorization: `Bearer ${accessToken}`
      }
    });
    return response.json;
  }
  async refreshAccessToken() {
    if (!this.settings.refreshToken) {
      return false;
    }
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: `${OAUTH_SERVER}/auth/refresh`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ refresh_token: this.settings.refreshToken })
      });
      const tokens = response.json;
      if (tokens.error) {
        throw new Error(tokens.error);
      }
      this.settings.accessToken = tokens.access_token;
      this.settings.tokenExpiry = Date.now() + tokens.expires_in * 1e3;
      await this.saveSettings();
      return true;
    } catch (error) {
      console.error("Token refresh failed:", error);
      return false;
    }
  }
  async getValidAccessToken() {
    if (Date.now() > this.settings.tokenExpiry - 6e4) {
      const refreshed = await this.refreshAccessToken();
      if (!refreshed) {
        new import_obsidian.Notice("Session expired. Please sign in again.");
        return null;
      }
    }
    return this.settings.accessToken;
  }
  async signOut() {
    this.settings.accessToken = "";
    this.settings.refreshToken = "";
    this.settings.tokenExpiry = 0;
    this.settings.userEmail = "";
    await this.saveSettings();
    if (this.syncInterval) {
      window.clearInterval(this.syncInterval);
      this.syncInterval = null;
    }
    new import_obsidian.Notice("Signed out from Google Drive.");
  }
  // =========================================================================
  // Public API for DataviewJS (audio player)
  // =========================================================================
  /**
   * Fetch a file from Google Drive by ID.
   * Used by DataviewJS audio player to stream music files.
   * Token is handled internally - never exposed to caller.
   */
  async fetchDriveFile(fileId) {
    const token = await this.getValidAccessToken();
    if (!token) {
      throw new Error("Not authenticated with Google Drive");
    }
    const response = await (0, import_obsidian.requestUrl)({
      url: `https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`,
      method: "GET",
      headers: {
        Authorization: `Bearer ${token}`
      }
    });
    return response.arrayBuffer;
  }
  // =========================================================================
  // Google Drive API
  // =========================================================================
  async driveRequest(endpoint, method = "GET", body, contentType) {
    const token = await this.getValidAccessToken();
    if (!token) {
      throw new Error("Not authenticated");
    }
    const headers = {
      Authorization: `Bearer ${token}`
    };
    if (contentType) {
      headers["Content-Type"] = contentType;
    }
    const response = await (0, import_obsidian.requestUrl)({
      url: `https://www.googleapis.com/drive/v3/${endpoint}`,
      method,
      headers,
      body
    });
    return response.json;
  }
  async findOrCreateFolder(path) {
    const parts = path.split("/").filter((p) => p);
    let parentId = "root";
    for (const part of parts) {
      const query = `name='${part}' and '${parentId}' in parents and mimeType='application/vnd.google-apps.folder' and trashed=false`;
      const searchResult = await this.driveRequest(
        `files?q=${encodeURIComponent(query)}&fields=files(id,name)`
      );
      if (searchResult.files && searchResult.files.length > 0) {
        parentId = searchResult.files[0].id;
      } else {
        const metadata = {
          name: part,
          mimeType: "application/vnd.google-apps.folder",
          parents: [parentId]
        };
        const created = await this.driveRequest(
          "files?fields=id",
          "POST",
          JSON.stringify(metadata),
          "application/json"
        );
        parentId = created.id;
      }
    }
    return parentId;
  }
  async listDriveFiles(folderId) {
    const files = [];
    let pageToken;
    do {
      const query = `'${folderId}' in parents and trashed=false`;
      let url = `files?q=${encodeURIComponent(query)}&fields=nextPageToken,files(id,name,mimeType,modifiedTime,md5Checksum,parents)`;
      if (pageToken) {
        url += `&pageToken=${pageToken}`;
      }
      const result = await this.driveRequest(url);
      if (result.files) {
        files.push(...result.files);
      }
      pageToken = result.nextPageToken;
    } while (pageToken);
    return files;
  }
  async downloadFile(fileId) {
    const token = await this.getValidAccessToken();
    if (!token) {
      throw new Error("Not authenticated");
    }
    const response = await (0, import_obsidian.requestUrl)({
      url: `https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`,
      method: "GET",
      headers: {
        Authorization: `Bearer ${token}`
      }
    });
    return response.text;
  }
  async uploadFile(name, content, parentId, existingFileId) {
    const token = await this.getValidAccessToken();
    if (!token) {
      throw new Error("Not authenticated");
    }
    const metadata = {
      name,
      ...existingFileId ? {} : { parents: [parentId] }
    };
    const boundary = "-------314159265358979323846";
    const delimiter = "\r\n--" + boundary + "\r\n";
    const closeDelim = "\r\n--" + boundary + "--";
    const body = delimiter + "Content-Type: application/json; charset=UTF-8\r\n\r\n" + JSON.stringify(metadata) + delimiter + "Content-Type: text/markdown\r\n\r\n" + content + closeDelim;
    const url = existingFileId ? `https://www.googleapis.com/upload/drive/v3/files/${existingFileId}?uploadType=multipart&fields=id` : `https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id`;
    const response = await (0, import_obsidian.requestUrl)({
      url,
      method: existingFileId ? "PATCH" : "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": `multipart/related; boundary="${boundary}"`
      },
      body
    });
    return response.json.id;
  }
  showProgressNotice() {
    if (this.currentNotice && document.body.contains(this.currentNotice.noticeEl)) {
      return;
    }
    const noticeEl = document.createDocumentFragment();
    const container = noticeEl.createDiv({ cls: "vectrola-progress-container" });
    const headerRow = container.createDiv({ cls: "vectrola-progress-header" });
    const label = headerRow.createDiv({ cls: "vectrola-progress-label", text: "\u{1F504} Syncing..." });
    const cancelBtn = headerRow.createEl("button", { cls: "vectrola-cancel-btn", text: "\u2715" });
    const progressBar = container.createDiv({ cls: "vectrola-progress-bar" });
    const progressFill = progressBar.createDiv({ cls: "vectrola-progress-fill" });
    const progressText = container.createDiv({ cls: "vectrola-progress-text", text: "0/0" });
    this.currentNotice = new import_obsidian.Notice(noticeEl, 0);
    this.noticeContent = { label, progressFill, progressText };
    cancelBtn.onclick = (e) => {
      var _a;
      e.stopPropagation();
      this.syncCancelled = true;
      (_a = this.currentNotice) == null ? void 0 : _a.hide();
      this.currentNotice = null;
      this.noticeContent = null;
      new import_obsidian.Notice("\u{1F6AB} Sync cancelled");
    };
    this.updateProgressDisplay();
  }
  updateProgressDisplay() {
    if (!this.noticeContent)
      return;
    const { label, progressFill, progressText } = this.noticeContent;
    const current = this.syncStats.processed;
    const total = this.syncStats.total;
    const pct = total > 0 ? Math.round(current / total * 100) : 0;
    label.textContent = `\u2B07\uFE0F ${this.syncStats.downloaded} \u23ED\uFE0F ${this.syncStats.skipped}`;
    progressFill.style.width = `${pct}%`;
    progressText.textContent = `${current}/${total}`;
  }
  async syncFromDrive() {
    var _a, _b;
    if (!this.isAuthenticated()) {
      new import_obsidian.Notice("Please sign in with Google Drive first.");
      return;
    }
    if (this.isSyncing) {
      this.showProgressNotice();
      return;
    }
    this.isSyncing = true;
    this.syncCancelled = false;
    this.syncStats = { processed: 0, downloaded: 0, skipped: 0, total: 0 };
    this.showProgressNotice();
    if (this.noticeContent) {
      this.noticeContent.label.textContent = "\u{1F504} Connecting...";
    }
    try {
      if (this.noticeContent) {
        this.noticeContent.label.textContent = `\u{1F504} Finding folder...`;
      }
      const folderId = await this.findOrCreateFolder(this.settings.driveFolderPath);
      if (this.syncCancelled) {
        this.isSyncing = false;
        return;
      }
      if (this.noticeContent) {
        this.noticeContent.label.textContent = "\u{1F504} Counting files...";
      }
      this.syncStats.total = await this.countDriveFiles(folderId);
      this.updateProgressDisplay();
      if (this.syncCancelled) {
        this.isSyncing = false;
        return;
      }
      await this.syncFolderFromDrive(folderId, "", () => {
        this.updateProgressDisplay();
      });
      if (this.syncCancelled) {
        this.isSyncing = false;
        return;
      }
      this.settings.lastSyncTime = Date.now();
      await this.saveSettings();
      (_a = this.currentNotice) == null ? void 0 : _a.hide();
      this.currentNotice = null;
      this.noticeContent = null;
      if (this.syncStats.skipped > 0) {
        new import_obsidian.Notice(`\u2705 Sync complete! ${this.syncStats.downloaded} downloaded, ${this.syncStats.skipped} skipped`);
      } else {
        new import_obsidian.Notice(`\u2705 Sync complete! ${this.syncStats.downloaded} files downloaded`);
      }
    } catch (error) {
      if (!this.syncCancelled) {
        console.error("Sync failed:", error);
        (_b = this.currentNotice) == null ? void 0 : _b.hide();
        new import_obsidian.Notice(`\u274C Sync failed: ${error.message}`);
      }
      this.currentNotice = null;
      this.noticeContent = null;
    } finally {
      this.isSyncing = false;
    }
  }
  async countDriveFiles(folderId) {
    if (this.syncCancelled)
      return 0;
    const driveFiles = await this.listDriveFiles(folderId);
    let count = 0;
    for (const file of driveFiles) {
      if (this.syncCancelled)
        return count;
      if (file.mimeType === "application/vnd.google-apps.folder") {
        count += await this.countDriveFiles(file.id);
      } else if (file.name.endsWith(".md")) {
        count++;
      }
    }
    return count;
  }
  async syncFolderFromDrive(folderId, localPath, onProgress) {
    if (this.syncCancelled)
      return;
    const driveFiles = await this.listDriveFiles(folderId);
    for (const file of driveFiles) {
      if (this.syncCancelled)
        return;
      const filePath = localPath ? `${localPath}/${file.name}` : file.name;
      if (file.mimeType === "application/vnd.google-apps.folder") {
        const folder = this.app.vault.getAbstractFileByPath(filePath);
        if (!folder) {
          try {
            await this.app.vault.createFolder(filePath);
          } catch (e) {
          }
        }
        await this.syncFolderFromDrive(file.id, filePath, onProgress);
      } else if (file.name.endsWith(".md")) {
        const cachedHash = this.settings.syncCache[filePath];
        if (cachedHash && file.md5Checksum && cachedHash === file.md5Checksum) {
          this.syncStats.processed++;
          this.syncStats.skipped++;
          if (onProgress)
            onProgress(this.syncStats.processed);
          continue;
        }
        this.syncStats.processed++;
        this.syncStats.downloaded++;
        if (onProgress)
          onProgress(this.syncStats.processed);
        const content = await this.downloadFile(file.id);
        const existingFile = this.app.vault.getAbstractFileByPath(filePath);
        if (existingFile instanceof import_obsidian.TFile) {
          await this.app.vault.modify(existingFile, content);
        } else {
          try {
            await this.app.vault.create(filePath, content);
          } catch (e) {
            const retryFile = this.app.vault.getAbstractFileByPath(filePath);
            if (retryFile instanceof import_obsidian.TFile) {
              await this.app.vault.modify(retryFile, content);
            }
          }
        }
        if (file.md5Checksum) {
          this.settings.syncCache[filePath] = file.md5Checksum;
        }
      }
    }
  }
  async syncToDrive() {
    var _a, _b, _c;
    if (!this.isAuthenticated()) {
      new import_obsidian.Notice("Please sign in with Google Drive first.");
      return;
    }
    new import_obsidian.Notice("Pushing to Google Drive...");
    try {
      const folderId = await this.findOrCreateFolder(this.settings.driveFolderPath);
      const files = this.app.vault.getMarkdownFiles();
      let uploaded = 0;
      for (const file of files) {
        const content = await this.app.vault.read(file);
        const parentPath = ((_a = file.parent) == null ? void 0 : _a.path) || "";
        const driveParentPath = parentPath ? `${this.settings.driveFolderPath}/${parentPath}` : this.settings.driveFolderPath;
        const parentFolderId = await this.findOrCreateFolder(driveParentPath);
        const query = `name='${file.name}' and '${parentFolderId}' in parents and trashed=false`;
        const existing = await this.driveRequest(
          `files?q=${encodeURIComponent(query)}&fields=files(id)`
        );
        const existingId = (_c = (_b = existing.files) == null ? void 0 : _b[0]) == null ? void 0 : _c.id;
        await this.uploadFile(file.name, content, parentFolderId, existingId);
        uploaded++;
      }
      this.settings.lastSyncTime = Date.now();
      await this.saveSettings();
      new import_obsidian.Notice(`Pushed ${uploaded} files to Google Drive!`);
    } catch (error) {
      console.error("Push failed:", error);
      new import_obsidian.Notice(`Push failed: ${error.message}`);
    }
  }
};
var AuthCodeModal = class extends import_obsidian.Modal {
  constructor(app, callback) {
    super(app);
    this.callback = callback;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Paste Authorization Code" });
    contentEl.createEl("p", {
      text: "A browser window opened. After signing in, copy the code shown and paste it here:"
    });
    this.inputEl = new import_obsidian.TextComponent(contentEl);
    this.inputEl.inputEl.addClass("vectrola-input-full-width");
    this.inputEl.inputEl.placeholder = "Paste code here...";
    const buttonContainer = contentEl.createDiv({ cls: "vectrola-button-container" });
    const cancelBtn = buttonContainer.createEl("button", { text: "Cancel" });
    cancelBtn.onclick = () => {
      this.callback(null);
      this.close();
    };
    const submitBtn = buttonContainer.createEl("button", {
      text: "Connect",
      cls: "mod-cta"
    });
    submitBtn.onclick = () => {
      const code = this.inputEl.getValue().trim();
      this.callback(code || null);
      this.close();
    };
    setTimeout(() => this.inputEl.inputEl.focus(), 100);
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var VectrolaSyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Connection").setHeading();
    if (this.plugin.isAuthenticated()) {
      const statusBox = containerEl.createEl("div", { cls: "vectrola-status-box" });
      const statusContainer = statusBox.createEl("div", { cls: "vectrola-status-container" });
      statusContainer.createEl("span", { cls: "vectrola-status-icon", text: "\u2705" });
      const statusText = statusContainer.createEl("div", { cls: "vectrola-status-text" });
      statusText.createEl("div", { cls: "vectrola-status-title", text: "Connected to Google Drive" });
      if (this.plugin.settings.userEmail) {
        statusText.createEl("div", { cls: "vectrola-status-subtitle", text: this.plugin.settings.userEmail });
      }
      new import_obsidian.Setting(containerEl).setName("Sign out").setDesc("Disconnect from Google Drive").addButton(
        (btn) => btn.setButtonText("Sign Out").setWarning().onClick(async () => {
          await this.plugin.signOut();
          this.display();
        })
      );
    } else {
      const statusBox = containerEl.createEl("div", { cls: "vectrola-status-box" });
      const statusContainer = statusBox.createEl("div", { cls: "vectrola-status-container" });
      statusContainer.createEl("span", { cls: "vectrola-status-icon", text: "\u{1F517}" });
      const statusText = statusContainer.createEl("div", { cls: "vectrola-status-text" });
      statusText.createEl("div", { cls: "vectrola-status-title", text: "Not connected" });
      statusText.createEl("div", { cls: "vectrola-status-subtitle", text: "Sign in to sync your music wiki" });
      new import_obsidian.Setting(containerEl).setName("Sign in with Google").setDesc("Connect to Google Drive to sync your wiki").addButton(
        (btn) => btn.setButtonText("Sign in with Google").setCta().onClick(async () => {
          await this.plugin.authenticate();
          this.display();
        })
      );
    }
    new import_obsidian.Setting(containerEl).setName("Synchronization").setHeading();
    new import_obsidian.Setting(containerEl).setName("Drive folder path").setDesc("Google Drive folder where wiki is stored").addText(
      (text) => text.setPlaceholder("/Vectrola/wiki").setValue(this.plugin.settings.driveFolderPath).onChange(async (value) => {
        this.plugin.settings.driveFolderPath = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto-sync on open").setDesc("Automatically pull from Drive when vault opens").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoSyncOnOpen).onChange(async (value) => {
        this.plugin.settings.autoSyncOnOpen = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Sync interval (minutes)").setDesc("How often to sync automatically (0 to disable)").addText(
      (text) => text.setPlaceholder("5").setValue(String(this.plugin.settings.syncIntervalMinutes)).onChange(async (value) => {
        const num = parseInt(value) || 0;
        this.plugin.settings.syncIntervalMinutes = num;
        await this.plugin.saveSettings();
        this.plugin.setupSyncInterval();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Manual Sync").setHeading();
    new import_obsidian.Setting(containerEl).setName("Pull from Drive").setDesc("Download latest wiki from Google Drive").addButton(
      (btn) => btn.setButtonText("Pull").onClick(async () => {
        await this.plugin.syncFromDrive();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Push to Drive").setDesc("Upload current vault to Google Drive").addButton(
      (btn) => btn.setButtonText("Push").onClick(async () => {
        await this.plugin.syncToDrive();
      })
    );
    if (this.plugin.settings.lastSyncTime > 0) {
      const lastSync = new Date(this.plugin.settings.lastSyncTime).toLocaleString();
      containerEl.createEl("p", {
        text: `Last synced: ${lastSync}`,
        cls: "setting-item-description"
      });
    }
  }
};
