/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => VectrolaSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// src/icons.ts
var ICONS = {
  // Playback controls
  play: `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M8 5v14l11-7z"/></svg>`,
  pause: `<svg viewBox="0 0 24 24" fill="currentColor"><rect x="6" y="4" width="4" height="16" rx="1"/><rect x="14" y="4" width="4" height="16" rx="1"/></svg>`,
  previous: `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M6 6h2v12H6zm3.5 6l8.5 6V6z"/></svg>`,
  next: `<svg viewBox="0 0 24 24" fill="currentColor"><path d="M6 18l8.5-6L6 6v12zM16 6v12h2V6h-2z"/></svg>`,
  // Shuffle - crossed arrows
  shuffle: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
    <polyline points="16 3 21 3 21 8"/>
    <line x1="4" y1="20" x2="21" y2="3"/>
    <polyline points="21 16 21 21 16 21"/>
    <line x1="15" y1="15" x2="21" y2="21"/>
    <line x1="4" y1="4" x2="9" y2="9"/>
  </svg>`,
  // Repeat - circular arrows
  repeat: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
    <polyline points="17 1 21 5 17 9"/>
    <path d="M3 11V9a4 4 0 0 1 4-4h14"/>
    <polyline points="7 23 3 19 7 15"/>
    <path d="M21 13v2a4 4 0 0 1-4 4H3"/>
  </svg>`,
  // Repeat one - with "1" indicator
  repeatOne: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
    <polyline points="17 1 21 5 17 9"/>
    <path d="M3 11V9a4 4 0 0 1 4-4h14"/>
    <polyline points="7 23 3 19 7 15"/>
    <path d="M21 13v2a4 4 0 0 1-4 4H3"/>
    <text x="12" y="14" font-size="8" fill="currentColor" stroke="none" text-anchor="middle" dominant-baseline="middle" font-weight="bold">1</text>
  </svg>`,
  // Volume - Apple Music style: speaker pointing left + 2 curved arcs
  volume: `<svg viewBox="0 0 24 24" fill="currentColor">
    <path d="M3 9v6h4l5 5V4L7 9H3z"/>
    <path d="M14 9.5c1 .7 1.5 1.7 1.5 2.5s-.5 1.8-1.5 2.5" stroke="currentColor" stroke-width="1.5" fill="none" stroke-linecap="round"/>
    <path d="M17 7c1.5 1.2 2.5 3 2.5 5s-1 3.8-2.5 5" stroke="currentColor" stroke-width="1.5" fill="none" stroke-linecap="round"/>
  </svg>`,
  // Volume mute - speaker with X
  volumeMute: `<svg viewBox="0 0 24 24" fill="currentColor">
    <path d="M3 9v6h4l5 5V4L7 9H3z"/>
    <line x1="16" y1="9" x2="22" y2="15" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
    <line x1="22" y1="9" x2="16" y2="15" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
  </svg>`,
  // Music note - fallback for missing artwork
  music: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
    <path d="M9 18V5l12-2v13"/>
    <circle cx="6" cy="18" r="3"/>
    <circle cx="18" cy="16" r="3"/>
  </svg>`,
  // More options - horizontal dots
  more: `<svg viewBox="0 0 24 24" fill="currentColor">
    <circle cx="5" cy="12" r="2"/>
    <circle cx="12" cy="12" r="2"/>
    <circle cx="19" cy="12" r="2"/>
  </svg>`
};

// src/main.ts
var GOOGLE_CLIENT_ID = "212647824656-9h9gchm0msibletsog338miabe9qtbe1.apps.googleusercontent.com";
var OAUTH_SERVER = "https://vectrola-oauth.up.railway.app";
var REDIRECT_URI = `${OAUTH_SERVER}/callback`;
var SCOPES = "https://www.googleapis.com/auth/drive.readonly https://www.googleapis.com/auth/drive.file";
var DEFAULT_SETTINGS = {
  accessToken: "",
  refreshToken: "",
  tokenExpiry: 0,
  userEmail: "",
  driveFolderPath: "/Vectrola/wiki",
  autoSyncOnOpen: true,
  syncIntervalMinutes: 5,
  lastSyncTime: 0,
  syncCache: {}
};
function generateCodeVerifier() {
  const array = new Uint8Array(32);
  crypto.getRandomValues(array);
  return base64UrlEncode(array);
}
async function generateCodeChallenge(verifier) {
  const encoder = new TextEncoder();
  const data = encoder.encode(verifier);
  const digest = await crypto.subtle.digest("SHA-256", data);
  return base64UrlEncode(new Uint8Array(digest));
}
function generateRandomState() {
  const array = new Uint8Array(16);
  crypto.getRandomValues(array);
  return base64UrlEncode(array);
}
function base64UrlEncode(buffer) {
  let binary = "";
  for (let i = 0; i < buffer.length; i++) {
    binary += String.fromCharCode(buffer[i]);
  }
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}
var VectrolaSyncPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.syncInterval = null;
    // Pending auth state for CSRF protection
    this.pendingAuthState = null;
    // Event emitter for auth state changes
    this.events = new import_obsidian.Events();
    // =========================================================================
    // Sync Operations
    // =========================================================================
    this.syncStats = { processed: 0, downloaded: 0, skipped: 0, total: 0 };
    this.syncCancelled = false;
    this.isSyncing = false;
    this.currentNotice = null;
    this.noticeContent = null;
  }
  async onload() {
    await this.loadSettings();
    this.registerObsidianProtocolHandler("vectrola-auth", (params) => {
      this.handleOAuthCallback(params);
    });
    this.registerMarkdownCodeBlockProcessor("vectrola", (source, el, ctx) => {
      this.renderVectrolaPlayer(source, el);
    });
    this.api = {
      fetchDriveFile: this.fetchDriveFile.bind(this),
      isAuthenticated: this.isAuthenticated.bind(this)
    };
    this.addRibbonIcon("refresh-cw", "Sync with Vectrola", async () => {
      await this.syncFromDrive();
    });
    this.addCommand({
      id: "vectrola-sync-pull",
      name: "Pull wiki from Google Drive",
      callback: async () => {
        await this.syncFromDrive();
      }
    });
    this.addCommand({
      id: "vectrola-sync-push",
      name: "Push wiki to Google Drive",
      callback: async () => {
        await this.syncToDrive();
      }
    });
    this.addCommand({
      id: "vectrola-auth",
      name: "Sign in with Google Drive",
      callback: async () => {
        await this.authenticate();
      }
    });
    this.addCommand({
      id: "vectrola-signout",
      name: "Sign out from Google Drive",
      callback: async () => {
        await this.signOut();
      }
    });
    this.addSettingTab(new VectrolaSyncSettingTab(this.app, this));
    if (this.settings.autoSyncOnOpen && this.isAuthenticated()) {
      setTimeout(() => this.syncFromDrive(), 3e3);
    }
    this.setupSyncInterval();
  }
  onunload() {
    if (this.syncInterval) {
      window.clearInterval(this.syncInterval);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  setupSyncInterval() {
    if (this.syncInterval) {
      window.clearInterval(this.syncInterval);
    }
    if (this.settings.syncIntervalMinutes > 0 && this.isAuthenticated()) {
      this.syncInterval = window.setInterval(
        () => this.syncFromDrive(),
        this.settings.syncIntervalMinutes * 60 * 1e3
      );
    }
  }
  isAuthenticated() {
    return !!(this.settings.accessToken && this.settings.refreshToken);
  }
  // =========================================================================
  // Vectrola Audio Player Renderer
  // =========================================================================
  renderVectrolaPlayer(source, container) {
    var _a, _b;
    try {
      const config = JSON.parse(source);
      const playlist = config.playlist || [];
      const pageTitle = config.title || "";
      if (!playlist.length) {
        container.createEl("p", { text: "No tracks available" });
        return;
      }
      if (!window.vectrolaPlayer) {
        window.vectrolaPlayer = {
          audio: new Audio(),
          currentTrack: null,
          currentIndex: -1,
          isPlaying: false,
          shuffleMode: false,
          repeatMode: "off",
          shuffleHistory: [],
          playlist: [],
          playlistSource: null,
          ui: null,
          overlayVisible: false,
          volume: 1
        };
        window.vectrolaPlayer.audio.preload = "none";
        this.setupAudioEventListeners();
      }
      const player = window.vectrolaPlayer;
      const playTrack = (index) => {
        player.playlist = playlist;
        player.playlistSource = pageTitle;
        this.playTrack(index);
      };
      const header = container.createEl("div");
      header.className = "vectrola-page-header";
      const artworkContainer = header.createEl("div");
      artworkContainer.className = "vectrola-header-artwork";
      if ((_a = config.artwork) == null ? void 0 : _a.url) {
        const img = artworkContainer.createEl("img");
        img.src = config.artwork.url;
        img.alt = pageTitle;
      } else {
        const gradient = this.getMoodGradient(((_b = playlist[0]) == null ? void 0 : _b.mood) || pageTitle);
        artworkContainer.addClass(gradient);
      }
      const titleOverlay = artworkContainer.createEl("div");
      titleOverlay.className = "vectrola-header-title-overlay";
      titleOverlay.textContent = pageTitle;
      const infoSection = header.createEl("div");
      infoSection.className = "vectrola-header-info";
      const titleEl = infoSection.createEl("h1");
      titleEl.className = "vectrola-header-name";
      titleEl.textContent = pageTitle;
      const descEl = infoSection.createEl("p");
      descEl.className = "vectrola-header-description";
      descEl.textContent = `${playlist.length} Songs`;
      const actionsEl = infoSection.createEl("div");
      actionsEl.className = "vectrola-header-actions";
      const playBtn = actionsEl.createEl("button");
      playBtn.className = "vectrola-header-btn vectrola-header-btn-play";
      playBtn.innerHTML = `${ICONS.play} Play`;
      playBtn.addEventListener("click", () => playTrack(0));
      const shuffleBtn = actionsEl.createEl("button");
      shuffleBtn.className = "vectrola-header-btn vectrola-header-btn-shuffle";
      shuffleBtn.innerHTML = `${ICONS.shuffle} Shuffle`;
      shuffleBtn.addEventListener("click", () => {
        player.shuffleMode = true;
        player.shuffleHistory = [];
        const randomIndex = Math.floor(Math.random() * playlist.length);
        playTrack(randomIndex);
      });
      const listHeader = container.createEl("div");
      listHeader.className = "vectrola-list-header";
      listHeader.innerHTML = `
				<span class="vectrola-col-song">Song</span>
				<span class="vectrola-col-artist">Artist</span>
				<span class="vectrola-col-album">Album</span>
				<span class="vectrola-col-time">Time</span>
			`;
      const trackListEl = container.createEl("div");
      trackListEl.className = "vectrola-track-list";
      const updateLocalHighlight = () => {
        trackListEl.querySelectorAll(".vectrola-track-row").forEach((row, i) => {
          const track = playlist[i];
          const isCurrentTrack = player.currentTrack && player.currentTrack.path === track.path;
          row.classList.toggle("is-playing", !!isCurrentTrack);
        });
      };
      playlist.forEach((track, i) => {
        const row = trackListEl.createEl("div");
        row.className = "vectrola-track-row";
        row.dataset.index = String(i);
        const thumb = row.createEl("div");
        thumb.className = "vectrola-track-row-thumbnail";
        if (track.artwork_url) {
          const img = thumb.createEl("img");
          img.src = track.artwork_url;
          img.alt = track.title;
        } else {
          thumb.addClass(this.getMoodGradient(track.mood));
          thumb.innerHTML = ICONS.music;
        }
        const equalizer = thumb.createEl("div");
        equalizer.className = "vectrola-equalizer";
        for (let b = 0; b < 3; b++) {
          equalizer.createEl("span", { cls: "vectrola-eq-bar" });
        }
        const info = row.createEl("div");
        info.className = "vectrola-track-row-info";
        const titleEl2 = info.createEl("div", { text: track.title });
        titleEl2.className = "vectrola-track-row-title";
        const subtitleEl = info.createEl("div", { text: track.artist });
        subtitleEl.className = "vectrola-track-row-subtitle";
        if (track.duration) {
          const durationEl = row.createEl("div", { text: track.duration });
          durationEl.className = "vectrola-track-row-duration";
        }
        const moreBtn = row.createEl("button");
        moreBtn.className = "vectrola-track-row-more";
        moreBtn.innerHTML = ICONS.more;
        moreBtn.title = "Track details";
        moreBtn.addEventListener("click", (e) => {
          e.stopPropagation();
          this.app.workspace.openLinkText(track.link, "", false);
        });
        row.addEventListener("click", () => {
          player.playlist = playlist;
          player.playlistSource = pageTitle;
          player.shuffleHistory = [];
          playTrack(i);
        });
      });
      this.ensurePlayerBar();
      updateLocalHighlight();
      if (!window.vectrolaHighlightUpdaters) {
        window.vectrolaHighlightUpdaters = /* @__PURE__ */ new Set();
      }
      window.vectrolaHighlightUpdaters.add(updateLocalHighlight);
      const observer = new MutationObserver(() => {
        var _a2;
        if (!document.contains(trackListEl)) {
          (_a2 = window.vectrolaHighlightUpdaters) == null ? void 0 : _a2.delete(updateLocalHighlight);
          observer.disconnect();
        }
      });
      observer.observe(document.body, { childList: true, subtree: true });
    } catch (e) {
      console.error("Failed to render Vectrola player:", e);
      container.createEl("p", { text: "Error loading player", cls: "vectrola-error" });
    }
  }
  setupAudioEventListeners() {
    const player = window.vectrolaPlayer;
    if (!player)
      return;
    player.audio.addEventListener("timeupdate", () => {
      const pf = document.getElementById("vectrola-progress-fill");
      const ct = document.getElementById("vectrola-current-time");
      if (player.audio.duration && pf && ct) {
        pf.style.width = player.audio.currentTime / player.audio.duration * 100 + "%";
        ct.textContent = this.formatTime(player.audio.currentTime);
      }
    });
    player.audio.addEventListener("loadedmetadata", () => {
      const tt = document.getElementById("vectrola-total-time");
      if (tt)
        tt.textContent = this.formatTime(player.audio.duration);
    });
    player.audio.addEventListener("ended", () => this.nextTrack());
  }
  formatTime(seconds) {
    if (isNaN(seconds))
      return "0:00";
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}:${secs.toString().padStart(2, "0")}`;
  }
  async playTrack(index) {
    var _a;
    const player = window.vectrolaPlayer;
    if (!player || index < 0 || index >= player.playlist.length)
      return;
    const track = player.playlist[index];
    try {
      if (player.audio.src && player.audio.src.startsWith("blob:")) {
        URL.revokeObjectURL(player.audio.src);
      }
      if (track.gdrive_id) {
        console.log("Playing from GDrive:", track.gdrive_id);
        try {
          if (this.isAuthenticated()) {
            const arrayBuffer = await this.fetchDriveFile(track.gdrive_id);
            const blob = new Blob([arrayBuffer], { type: "audio/mpeg" });
            const blobUrl = URL.createObjectURL(blob);
            player.audio.src = blobUrl;
            console.log("Playing via plugin API");
          } else {
            const fs = require("fs");
            const path = require("path");
            const os = require("os");
            const tokenPath = path.join(os.homedir(), ".config", "vectrola", "gdrive_token.json");
            const tokenData = JSON.parse(fs.readFileSync(tokenPath, "utf8"));
            const accessToken = tokenData.token;
            const response = await fetch(
              `https://www.googleapis.com/drive/v3/files/${track.gdrive_id}?alt=media`,
              { headers: { Authorization: `Bearer ${accessToken}` } }
            );
            if (!response.ok) {
              throw new Error(`GDrive fetch failed: ${response.status}`);
            }
            const arrayBuffer = await response.arrayBuffer();
            const blob = new Blob([arrayBuffer], { type: "audio/mpeg" });
            player.audio.src = URL.createObjectURL(blob);
            console.log("Playing via CLI token");
          }
        } catch (gdriveError) {
          console.error("GDrive playback failed, trying local:", gdriveError);
          if (track.path) {
            const fs = require("fs");
            const buffer = fs.readFileSync(track.path);
            const blob = new Blob([buffer], { type: "audio/mpeg" });
            player.audio.src = URL.createObjectURL(blob);
          } else {
            throw gdriveError;
          }
        }
      } else if (track.path) {
        console.log("Playing from local:", track.path);
        try {
          const fs = require("fs");
          const buffer = fs.readFileSync(track.path);
          const blob = new Blob([buffer], { type: "audio/mpeg" });
          const blobUrl = URL.createObjectURL(blob);
          player.audio.src = blobUrl;
        } catch (e) {
          console.error("Local file not found:", track.path, e);
          if (index + 1 < player.playlist.length) {
            this.playTrack(index + 1);
          }
          return;
        }
      } else {
        console.warn("No playback source for track:", track.title);
        return;
      }
      player.currentIndex = index;
      player.currentTrack = track;
      await player.audio.play();
      player.isPlaying = true;
      const titleEl = document.getElementById("vectrola-track-title");
      const artistEl = document.getElementById("vectrola-track-artist");
      const ppBtn = document.getElementById("vectrola-playpause-btn");
      const thumbnail = document.getElementById("vectrola-thumbnail");
      const artistContainer = document.querySelector(".vectrola-track-artist-container");
      if (titleEl) {
        titleEl.innerHTML = "";
        const link = document.createElement("a");
        link.textContent = track.title;
        link.href = "#";
        link.addEventListener("click", (e) => {
          e.preventDefault();
          if (track.link) {
            this.app.workspace.openLinkText(track.link, "", false);
          }
        });
        titleEl.appendChild(link);
      }
      if (artistEl)
        artistEl.textContent = track.artist;
      if (ppBtn)
        ppBtn.innerHTML = ICONS.pause;
      this.updateThumbnail(track);
      thumbnail == null ? void 0 : thumbnail.classList.add("is-playing");
      artistContainer == null ? void 0 : artistContainer.classList.add("is-playing");
      if (player.overlayVisible) {
        this.updateOverlayContent();
      }
      (_a = window.vectrolaHighlightUpdaters) == null ? void 0 : _a.forEach((fn) => fn());
      if (player.shuffleMode && !player.shuffleHistory.includes(index)) {
        player.shuffleHistory.push(index);
      }
    } catch (e) {
      console.error("Playback failed:", e);
    }
  }
  togglePlayPause() {
    var _a, _b, _c, _d;
    const player = window.vectrolaPlayer;
    if (!player)
      return;
    if (player.currentIndex === -1) {
      if (player.playlist.length > 0) {
        this.playTrack(0);
      }
      return;
    }
    const ppBtn = document.getElementById("vectrola-playpause-btn");
    if (player.isPlaying) {
      player.audio.pause();
      player.isPlaying = false;
      if (ppBtn)
        ppBtn.innerHTML = ICONS.play;
      (_a = document.querySelector(".vectrola-track-artist-container")) == null ? void 0 : _a.classList.remove("is-playing");
      (_b = document.getElementById("vectrola-thumbnail")) == null ? void 0 : _b.classList.remove("is-playing");
    } else {
      player.audio.play().catch((e) => console.error("Playback failed:", e));
      player.isPlaying = true;
      if (ppBtn)
        ppBtn.innerHTML = ICONS.pause;
      (_c = document.querySelector(".vectrola-track-artist-container")) == null ? void 0 : _c.classList.add("is-playing");
      (_d = document.getElementById("vectrola-thumbnail")) == null ? void 0 : _d.classList.add("is-playing");
    }
  }
  nextTrack() {
    const player = window.vectrolaPlayer;
    if (!player || !player.playlist.length)
      return;
    if (player.repeatMode === "one") {
      player.audio.currentTime = 0;
      player.audio.play().catch((e) => console.error("Playback failed:", e));
      return;
    }
    if (player.shuffleMode) {
      const unplayed = player.playlist.map((_, i) => i).filter((i) => !player.shuffleHistory.includes(i));
      if (unplayed.length === 0) {
        if (player.repeatMode === "all") {
          player.shuffleHistory = [];
          this.nextTrack();
        }
        return;
      }
      const randomIndex = unplayed[Math.floor(Math.random() * unplayed.length)];
      this.playTrack(randomIndex);
    } else {
      const nextIndex = (player.currentIndex + 1) % player.playlist.length;
      if (nextIndex === 0 && player.repeatMode === "off") {
        return;
      }
      this.playTrack(nextIndex);
    }
  }
  prevTrack() {
    const player = window.vectrolaPlayer;
    if (!player || !player.playlist.length)
      return;
    if (player.shuffleMode && player.shuffleHistory.length > 1) {
      player.shuffleHistory.pop();
      this.playTrack(player.shuffleHistory[player.shuffleHistory.length - 1]);
    } else {
      this.playTrack(player.currentIndex <= 0 ? player.playlist.length - 1 : player.currentIndex - 1);
    }
  }
  toggleShuffle() {
    const player = window.vectrolaPlayer;
    if (!player)
      return;
    player.shuffleMode = !player.shuffleMode;
    const sBtn = document.getElementById("vectrola-shuffle-btn");
    if (sBtn) {
      sBtn.classList.toggle("is-active", player.shuffleMode);
      this.flashButton(sBtn);
    }
    if (!player.shuffleMode) {
      player.shuffleHistory = [];
    } else if (player.currentIndex >= 0) {
      player.shuffleHistory = [player.currentIndex];
    }
  }
  toggleRepeat() {
    const player = window.vectrolaPlayer;
    if (!player)
      return;
    if (player.repeatMode === "off") {
      player.repeatMode = "all";
    } else if (player.repeatMode === "all") {
      player.repeatMode = "one";
    } else {
      player.repeatMode = "off";
    }
    const rBtn = document.getElementById("vectrola-repeat-btn");
    if (rBtn) {
      rBtn.classList.toggle("is-active", player.repeatMode !== "off");
      if (player.repeatMode === "one") {
        rBtn.innerHTML = ICONS.repeatOne;
      } else {
        rBtn.innerHTML = ICONS.repeat;
      }
      this.flashButton(rBtn);
    }
  }
  flashButton(btn) {
    btn.classList.add("is-clicked");
    setTimeout(() => btn.classList.remove("is-clicked"), 300);
  }
  calculatePlayerPosition() {
    const margin = 16;
    let bottomPx = margin;
    let leftPx = margin;
    let rightPx = margin;
    if (import_obsidian.Platform.isMobileApp) {
      const mobileNav = document.querySelector(".mobile-navbar");
      if (mobileNav) {
        const rect = mobileNav.getBoundingClientRect();
        bottomPx = window.innerHeight - rect.top + margin;
      }
    } else {
      const statusBar = document.querySelector(".status-bar");
      if (statusBar) {
        const rect = statusBar.getBoundingClientRect();
        bottomPx = window.innerHeight - rect.top + margin;
      }
    }
    const leftSplit = document.querySelector(".workspace-split.mod-left-split");
    if (leftSplit) {
      const rect = leftSplit.getBoundingClientRect();
      if (rect.width > 0) {
        leftPx = rect.right + margin;
      }
    }
    const rightSplit = document.querySelector(".workspace-split.mod-right-split");
    if (rightSplit) {
      const rect = rightSplit.getBoundingClientRect();
      if (rect.width > 0) {
        rightPx = window.innerWidth - rect.left + margin;
      }
    }
    const availableWidth = window.innerWidth - leftPx - rightPx;
    const maxPlayerWidth = 800;
    const playerWidth = Math.min(availableWidth, maxPlayerWidth);
    const centeredLeft = leftPx + (availableWidth - playerWidth) / 2;
    const bottomValue = import_obsidian.Platform.isMobileApp ? `calc(${bottomPx}px + env(safe-area-inset-bottom, 0px))` : `${bottomPx}px`;
    return {
      bottom: bottomValue,
      left: `${Math.max(centeredLeft, margin)}px`,
      width: `${playerWidth}px`
    };
  }
  getMoodGradient(mood) {
    if (!mood)
      return "vectrola-gradient-default";
    const m = mood.toLowerCase();
    if (m.includes("melanchol") || m.includes("sad") || m.includes("sorrow"))
      return "vectrola-gradient-melancholic";
    if (m.includes("romantic") || m.includes("love") || m.includes("passion"))
      return "vectrola-gradient-romantic";
    if (m.includes("upbeat") || m.includes("party") || m.includes("dance") || m.includes("happy") || m.includes("joy"))
      return "vectrola-gradient-upbeat";
    if (m.includes("chill") || m.includes("relax") || m.includes("peaceful") || m.includes("calm"))
      return "vectrola-gradient-chill";
    return "vectrola-gradient-default";
  }
  createThumbnail(track) {
    const container = document.createElement("div");
    container.className = "vectrola-thumbnail";
    container.id = "vectrola-thumbnail";
    if (track == null ? void 0 : track.artwork_url) {
      const img = document.createElement("img");
      img.src = track.artwork_url;
      img.alt = track.title;
      img.loading = "lazy";
      img.onerror = () => {
        container.innerHTML = "";
        const gradient = document.createElement("div");
        gradient.className = `vectrola-thumbnail-gradient ${this.getMoodGradient(track.mood)}`;
        gradient.innerHTML = ICONS.music;
        container.appendChild(gradient);
      };
      container.appendChild(img);
    } else {
      const gradient = document.createElement("div");
      gradient.className = `vectrola-thumbnail-gradient ${this.getMoodGradient(track == null ? void 0 : track.mood)}`;
      gradient.innerHTML = ICONS.music;
      container.appendChild(gradient);
    }
    return container;
  }
  createControlButton(iconName, id, extraClass) {
    const btn = document.createElement("button");
    btn.className = `vectrola-control-btn${extraClass ? ` ${extraClass}` : ""}`;
    if (id)
      btn.id = id;
    btn.innerHTML = ICONS[iconName];
    btn.addEventListener("click", () => this.flashButton(btn));
    return btn;
  }
  createControls() {
    const controls = document.createElement("div");
    controls.className = "vectrola-controls";
    const player = window.vectrolaPlayer;
    const shuffleBtn = this.createControlButton("shuffle", "vectrola-shuffle-btn");
    shuffleBtn.title = "Shuffle";
    if (player == null ? void 0 : player.shuffleMode)
      shuffleBtn.classList.add("is-active");
    shuffleBtn.addEventListener("click", () => this.toggleShuffle());
    const prevBtn = this.createControlButton("previous");
    prevBtn.title = "Previous";
    prevBtn.addEventListener("click", () => this.prevTrack());
    const playPauseBtn = this.createControlButton(
      (player == null ? void 0 : player.isPlaying) ? "pause" : "play",
      "vectrola-playpause-btn",
      "vectrola-playpause-btn"
    );
    playPauseBtn.title = "Play/Pause";
    playPauseBtn.addEventListener("click", () => this.togglePlayPause());
    const nextBtn = this.createControlButton("next");
    nextBtn.title = "Next";
    nextBtn.addEventListener("click", () => this.nextTrack());
    const repeatBtn = this.createControlButton(
      (player == null ? void 0 : player.repeatMode) === "one" ? "repeatOne" : "repeat",
      "vectrola-repeat-btn"
    );
    repeatBtn.title = "Repeat";
    if ((player == null ? void 0 : player.repeatMode) !== "off")
      repeatBtn.classList.add("is-active");
    repeatBtn.addEventListener("click", () => this.toggleRepeat());
    controls.append(shuffleBtn, prevBtn, playPauseBtn, nextBtn, repeatBtn);
    return controls;
  }
  createVolumeControl() {
    var _a, _b;
    const container = document.createElement("div");
    container.className = "vectrola-volume";
    const slider = document.createElement("input");
    slider.type = "range";
    slider.min = "0";
    slider.max = "100";
    slider.value = String(Math.round(((_b = (_a = window.vectrolaPlayer) == null ? void 0 : _a.volume) != null ? _b : 1) * 100));
    slider.className = "vectrola-volume-slider";
    slider.id = "vectrola-volume-slider";
    slider.addEventListener("input", (e) => {
      const value = parseInt(e.target.value);
      if (window.vectrolaPlayer) {
        window.vectrolaPlayer.audio.volume = value / 100;
        window.vectrolaPlayer.volume = value / 100;
      }
      this.updateVolumeIcon(value);
    });
    slider.addEventListener("click", (e) => e.stopPropagation());
    const volumeBtn = document.createElement("button");
    volumeBtn.className = "vectrola-volume-btn";
    volumeBtn.id = "vectrola-volume-btn";
    volumeBtn.innerHTML = ICONS.volume;
    volumeBtn.title = "Volume";
    volumeBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      container.classList.toggle("is-expanded");
    });
    document.addEventListener("click", (e) => {
      if (!container.contains(e.target)) {
        container.classList.remove("is-expanded");
      }
    });
    container.append(slider, volumeBtn);
    return container;
  }
  updateVolumeIcon(value) {
    const volumeBtn = document.getElementById("vectrola-volume-btn");
    if (volumeBtn) {
      volumeBtn.innerHTML = value === 0 ? ICONS.volumeMute : ICONS.volume;
    }
  }
  updateThumbnail(track) {
    var _a;
    const container = document.getElementById("vectrola-thumbnail");
    if (!container)
      return;
    container.innerHTML = "";
    container.classList.remove("is-playing");
    if (track == null ? void 0 : track.artwork_url) {
      const img = document.createElement("img");
      img.src = track.artwork_url;
      img.alt = track.title;
      img.loading = "lazy";
      img.onerror = () => {
        container.innerHTML = "";
        const gradient = document.createElement("div");
        gradient.className = `vectrola-thumbnail-gradient ${this.getMoodGradient(track.mood)}`;
        gradient.innerHTML = ICONS.music;
        container.appendChild(gradient);
      };
      container.appendChild(img);
    } else {
      const gradient = document.createElement("div");
      gradient.className = `vectrola-thumbnail-gradient ${this.getMoodGradient(track == null ? void 0 : track.mood)}`;
      gradient.innerHTML = ICONS.music;
      container.appendChild(gradient);
    }
    if ((_a = window.vectrolaPlayer) == null ? void 0 : _a.isPlaying) {
      container.classList.add("is-playing");
    }
  }
  showOverlay() {
    const player = window.vectrolaPlayer;
    if (!player)
      return;
    let backdrop = document.getElementById("vectrola-overlay-backdrop");
    if (!backdrop) {
      backdrop = document.createElement("div");
      backdrop.id = "vectrola-overlay-backdrop";
      backdrop.className = "vectrola-overlay-backdrop";
      backdrop.addEventListener("click", () => this.hideOverlay());
      document.body.appendChild(backdrop);
    }
    let overlay = document.getElementById("vectrola-overlay");
    if (!overlay) {
      overlay = document.createElement("div");
      overlay.id = "vectrola-overlay";
      overlay.className = "vectrola-overlay";
      const artwork = document.createElement("div");
      artwork.className = "vectrola-overlay-artwork";
      artwork.id = "vectrola-overlay-artwork";
      const info = document.createElement("div");
      info.className = "vectrola-overlay-info";
      const title = document.createElement("div");
      title.className = "vectrola-overlay-title";
      title.id = "vectrola-overlay-title";
      const artist = document.createElement("div");
      artist.className = "vectrola-overlay-artist";
      artist.id = "vectrola-overlay-artist";
      info.append(title, artist);
      const controls = this.createControls();
      controls.className = "vectrola-overlay-controls";
      overlay.append(artwork, info, controls);
      document.body.appendChild(overlay);
    }
    this.updateOverlayContent();
    const playerBar = document.getElementById("vectrola-global-player");
    if (playerBar) {
      const barRect = playerBar.getBoundingClientRect();
      overlay.style.bottom = `${window.innerHeight - barRect.top + 16}px`;
      overlay.style.left = `${Math.max(16, (window.innerWidth - 300) / 2)}px`;
    }
    requestAnimationFrame(() => {
      backdrop == null ? void 0 : backdrop.classList.add("is-visible");
      overlay == null ? void 0 : overlay.classList.add("is-visible");
    });
    player.overlayVisible = true;
  }
  hideOverlay() {
    const backdrop = document.getElementById("vectrola-overlay-backdrop");
    const overlay = document.getElementById("vectrola-overlay");
    backdrop == null ? void 0 : backdrop.classList.remove("is-visible");
    overlay == null ? void 0 : overlay.classList.remove("is-visible");
    if (window.vectrolaPlayer) {
      window.vectrolaPlayer.overlayVisible = false;
    }
  }
  toggleOverlay() {
    const player = window.vectrolaPlayer;
    if (!player)
      return;
    if (player.overlayVisible) {
      this.hideOverlay();
    } else {
      this.showOverlay();
    }
  }
  updateOverlayContent() {
    var _a;
    const track = (_a = window.vectrolaPlayer) == null ? void 0 : _a.currentTrack;
    if (!track)
      return;
    const artwork = document.getElementById("vectrola-overlay-artwork");
    const title = document.getElementById("vectrola-overlay-title");
    const artist = document.getElementById("vectrola-overlay-artist");
    if (artwork) {
      if (track.artwork_url) {
        artwork.innerHTML = `<img src="${track.artwork_url}" alt="${track.title}">`;
      } else {
        const gradient = this.getMoodGradient(track.mood);
        artwork.innerHTML = `<div class="vectrola-thumbnail-gradient ${gradient}" style="width:100%;height:100%;font-size:48px;display:flex;align-items:center;justify-content:center;">${ICONS.music}</div>`;
      }
    }
    if (title)
      title.textContent = track.title;
    if (artist)
      artist.textContent = track.artist;
  }
  ensurePlayerBar() {
    var _a;
    const player = window.vectrolaPlayer;
    if (!player)
      return;
    let playerBar = document.getElementById("vectrola-global-player");
    if (playerBar)
      return;
    playerBar = document.createElement("div");
    playerBar.id = "vectrola-global-player";
    playerBar.className = "vectrola-player-bar";
    const pos = this.calculatePlayerPosition();
    playerBar.style.bottom = pos.bottom;
    playerBar.style.left = pos.left;
    playerBar.style.width = pos.width;
    playerBar.style.right = "auto";
    const progressContainer = document.createElement("div");
    progressContainer.className = "vectrola-progress-container";
    progressContainer.id = "vectrola-progress-bar";
    const progressFill = document.createElement("div");
    progressFill.className = "vectrola-progress-fill";
    progressFill.id = "vectrola-progress-fill";
    progressContainer.appendChild(progressFill);
    progressContainer.addEventListener("click", (e) => {
      if (player.audio.duration) {
        const rect = progressContainer.getBoundingClientRect();
        const pos2 = (e.clientX - rect.left) / rect.width;
        player.audio.currentTime = pos2 * player.audio.duration;
      }
    });
    const content = document.createElement("div");
    content.className = "vectrola-content";
    const controls = this.createControls();
    const thumbnail = this.createThumbnail(player.currentTrack);
    thumbnail.addEventListener("click", () => this.toggleOverlay());
    const trackInfo = document.createElement("div");
    trackInfo.className = "vectrola-track-info";
    const trackTitle = document.createElement("div");
    trackTitle.className = "vectrola-track-title";
    trackTitle.id = "vectrola-track-title";
    if (player.currentTrack) {
      const link = document.createElement("a");
      link.textContent = player.currentTrack.title;
      link.href = "#";
      link.addEventListener("click", (e) => {
        var _a2;
        e.preventDefault();
        if ((_a2 = player.currentTrack) == null ? void 0 : _a2.link) {
          this.app.workspace.openLinkText(player.currentTrack.link, "", false);
        }
      });
      trackTitle.appendChild(link);
    } else {
      trackTitle.textContent = "Select a track";
    }
    const artistContainer = document.createElement("div");
    artistContainer.className = "vectrola-track-artist-container";
    if (player.isPlaying)
      artistContainer.classList.add("is-playing");
    const trackArtist = document.createElement("div");
    trackArtist.className = "vectrola-track-artist";
    trackArtist.id = "vectrola-track-artist";
    trackArtist.textContent = ((_a = player.currentTrack) == null ? void 0 : _a.artist) || "";
    artistContainer.appendChild(trackArtist);
    trackInfo.append(trackTitle, artistContainer);
    const timeDisplay = document.createElement("div");
    timeDisplay.className = "vectrola-time";
    const currentTime = document.createElement("span");
    currentTime.className = "vectrola-time-current";
    currentTime.id = "vectrola-current-time";
    currentTime.textContent = "0:00";
    const separator = document.createElement("span");
    separator.className = "vectrola-time-separator";
    separator.textContent = "/";
    const totalTime = document.createElement("span");
    totalTime.className = "vectrola-time-total";
    totalTime.id = "vectrola-total-time";
    totalTime.textContent = "0:00";
    timeDisplay.append(currentTime, separator, totalTime);
    const volume = this.createVolumeControl();
    content.append(controls, thumbnail, trackInfo, timeDisplay);
    if (!import_obsidian.Platform.isMobile) {
      content.appendChild(volume);
    }
    playerBar.append(progressContainer, content);
    document.body.appendChild(playerBar);
    player.ui = {
      playerBar,
      progressFill,
      trackTitle,
      trackArtist,
      thumbnail,
      currentTime,
      totalTime
    };
    const updatePosition = () => {
      const bar = document.getElementById("vectrola-global-player");
      if (bar) {
        const pos2 = this.calculatePlayerPosition();
        bar.style.bottom = pos2.bottom;
        bar.style.left = pos2.left;
        bar.style.width = pos2.width;
      }
    };
    window.addEventListener("resize", updatePosition);
    if (import_obsidian.Platform.isMobileApp) {
      window.addEventListener("orientationchange", () => {
        setTimeout(updatePosition, 100);
      });
    }
    if (player.isPlaying) {
      thumbnail.classList.add("is-playing");
      artistContainer.classList.add("is-playing");
    }
  }
  // =========================================================================
  // OAuth Authentication (Server-side token exchange)
  // =========================================================================
  async authenticate() {
    const codeVerifier = generateCodeVerifier();
    const codeChallenge = await generateCodeChallenge(codeVerifier);
    const state = generateRandomState();
    this.pendingAuthState = state;
    try {
      await (0, import_obsidian.requestUrl)({
        url: `${OAUTH_SERVER}/auth/start`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ state, code_verifier: codeVerifier })
      });
    } catch (error) {
      console.error("Failed to start auth session:", error);
      new import_obsidian.Notice("Failed to connect to auth server. Please try again.");
      this.pendingAuthState = null;
      return;
    }
    let authUrl = `https://accounts.google.com/o/oauth2/v2/auth?client_id=${encodeURIComponent(GOOGLE_CLIENT_ID)}&redirect_uri=${encodeURIComponent(REDIRECT_URI)}&response_type=code&scope=${encodeURIComponent(SCOPES)}&access_type=offline&prompt=consent&code_challenge=${codeChallenge}&code_challenge_method=S256&state=${state}`;
    if (this.settings.userEmail) {
      authUrl += `&login_hint=${encodeURIComponent(this.settings.userEmail)}`;
    }
    try {
      const { shell } = require("electron");
      shell.openExternal(authUrl);
    } catch (e) {
      window.open(authUrl);
    }
    new import_obsidian.Notice("\u{1F510} Complete sign-in in your browser...");
  }
  // Handle OAuth callback from obsidian://vectrola-auth
  async handleOAuthCallback(params) {
    const { access_token, refresh_token, expires_in, state, error } = params;
    if (state !== this.pendingAuthState) {
      console.error("OAuth state mismatch:", { expected: this.pendingAuthState, received: state });
      new import_obsidian.Notice("\u274C Authentication failed: Invalid session. Please try again.");
      return;
    }
    this.pendingAuthState = null;
    if (error || !access_token) {
      new import_obsidian.Notice(`\u274C Authentication failed: ${error || "No token received"}`);
      return;
    }
    this.settings.accessToken = access_token;
    if (refresh_token) {
      this.settings.refreshToken = refresh_token;
    }
    this.settings.tokenExpiry = Date.now() + parseInt(expires_in) * 1e3;
    try {
      const userInfo = await this.getUserInfo(access_token);
      if (userInfo.email) {
        this.settings.userEmail = userInfo.email;
      }
    } catch (e) {
    }
    await this.saveSettings();
    this.setupSyncInterval();
    this.events.trigger("auth-state-changed");
    new import_obsidian.Notice("\u2705 Successfully connected to Google Drive!");
  }
  async getUserInfo(accessToken) {
    const response = await (0, import_obsidian.requestUrl)({
      url: "https://www.googleapis.com/oauth2/v2/userinfo",
      method: "GET",
      headers: {
        Authorization: `Bearer ${accessToken}`
      }
    });
    return response.json;
  }
  async refreshAccessToken() {
    if (!this.settings.refreshToken) {
      return false;
    }
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: `${OAUTH_SERVER}/auth/refresh`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ refresh_token: this.settings.refreshToken })
      });
      const tokens = response.json;
      if (tokens.error) {
        throw new Error(tokens.error);
      }
      this.settings.accessToken = tokens.access_token;
      this.settings.tokenExpiry = Date.now() + tokens.expires_in * 1e3;
      await this.saveSettings();
      return true;
    } catch (error) {
      console.error("Token refresh failed:", error);
      return false;
    }
  }
  async getValidAccessToken() {
    if (Date.now() > this.settings.tokenExpiry - 6e4) {
      const refreshed = await this.refreshAccessToken();
      if (!refreshed) {
        new import_obsidian.Notice("Session expired. Please sign in again.");
        return null;
      }
    }
    return this.settings.accessToken;
  }
  async signOut() {
    this.settings.accessToken = "";
    this.settings.refreshToken = "";
    this.settings.tokenExpiry = 0;
    this.settings.userEmail = "";
    await this.saveSettings();
    if (this.syncInterval) {
      window.clearInterval(this.syncInterval);
      this.syncInterval = null;
    }
    new import_obsidian.Notice("Signed out from Google Drive.");
  }
  // =========================================================================
  // Public API for DataviewJS (audio player)
  // =========================================================================
  /**
   * Fetch a file from Google Drive by ID.
   * Used by DataviewJS audio player to stream music files.
   * Token is handled internally - never exposed to caller.
   */
  async fetchDriveFile(fileId) {
    const token = await this.getValidAccessToken();
    if (!token) {
      throw new Error("Not authenticated with Google Drive");
    }
    const response = await (0, import_obsidian.requestUrl)({
      url: `https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`,
      method: "GET",
      headers: {
        Authorization: `Bearer ${token}`
      }
    });
    return response.arrayBuffer;
  }
  // =========================================================================
  // Google Drive API
  // =========================================================================
  async driveRequest(endpoint, method = "GET", body, contentType) {
    const token = await this.getValidAccessToken();
    if (!token) {
      throw new Error("Not authenticated");
    }
    const headers = {
      Authorization: `Bearer ${token}`
    };
    if (contentType) {
      headers["Content-Type"] = contentType;
    }
    const response = await (0, import_obsidian.requestUrl)({
      url: `https://www.googleapis.com/drive/v3/${endpoint}`,
      method,
      headers,
      body
    });
    return response.json;
  }
  async findOrCreateFolder(path) {
    const parts = path.split("/").filter((p) => p);
    let parentId = "root";
    for (const part of parts) {
      const query = `name='${part}' and '${parentId}' in parents and mimeType='application/vnd.google-apps.folder' and trashed=false`;
      const searchResult = await this.driveRequest(
        `files?q=${encodeURIComponent(query)}&fields=files(id,name)`
      );
      if (searchResult.files && searchResult.files.length > 0) {
        parentId = searchResult.files[0].id;
      } else {
        const metadata = {
          name: part,
          mimeType: "application/vnd.google-apps.folder",
          parents: [parentId]
        };
        const created = await this.driveRequest(
          "files?fields=id",
          "POST",
          JSON.stringify(metadata),
          "application/json"
        );
        parentId = created.id;
      }
    }
    return parentId;
  }
  async listDriveFiles(folderId) {
    const files = [];
    let pageToken;
    do {
      const query = `'${folderId}' in parents and trashed=false`;
      let url = `files?q=${encodeURIComponent(query)}&fields=nextPageToken,files(id,name,mimeType,modifiedTime,md5Checksum,parents)`;
      if (pageToken) {
        url += `&pageToken=${pageToken}`;
      }
      const result = await this.driveRequest(url);
      if (result.files) {
        files.push(...result.files);
      }
      pageToken = result.nextPageToken;
    } while (pageToken);
    return files;
  }
  async downloadFile(fileId) {
    const token = await this.getValidAccessToken();
    if (!token) {
      throw new Error("Not authenticated");
    }
    const response = await (0, import_obsidian.requestUrl)({
      url: `https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`,
      method: "GET",
      headers: {
        Authorization: `Bearer ${token}`
      }
    });
    return response.text;
  }
  async uploadFile(name, content, parentId, existingFileId) {
    const token = await this.getValidAccessToken();
    if (!token) {
      throw new Error("Not authenticated");
    }
    const metadata = {
      name,
      ...existingFileId ? {} : { parents: [parentId] }
    };
    const boundary = "-------314159265358979323846";
    const delimiter = "\r\n--" + boundary + "\r\n";
    const closeDelim = "\r\n--" + boundary + "--";
    const body = delimiter + "Content-Type: application/json; charset=UTF-8\r\n\r\n" + JSON.stringify(metadata) + delimiter + "Content-Type: text/markdown\r\n\r\n" + content + closeDelim;
    const url = existingFileId ? `https://www.googleapis.com/upload/drive/v3/files/${existingFileId}?uploadType=multipart&fields=id` : `https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id`;
    const response = await (0, import_obsidian.requestUrl)({
      url,
      method: existingFileId ? "PATCH" : "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": `multipart/related; boundary="${boundary}"`
      },
      body
    });
    return response.json.id;
  }
  showProgressNotice() {
    if (this.currentNotice && document.body.contains(this.currentNotice.noticeEl)) {
      return;
    }
    const noticeEl = document.createDocumentFragment();
    const container = noticeEl.createDiv({ cls: "vectrola-sync-progress-container" });
    const headerRow = container.createDiv({ cls: "vectrola-sync-progress-header" });
    const label = headerRow.createDiv({ cls: "vectrola-sync-progress-label", text: "\u{1F504} Syncing..." });
    const cancelBtn = headerRow.createEl("button", { cls: "vectrola-cancel-btn", text: "\u2715" });
    const progressBar = container.createDiv({ cls: "vectrola-sync-progress-bar" });
    const progressFill = progressBar.createDiv({ cls: "vectrola-sync-progress-fill" });
    const progressText = container.createDiv({ cls: "vectrola-sync-progress-text", text: "0/0" });
    this.currentNotice = new import_obsidian.Notice(noticeEl, 0);
    this.noticeContent = { label, progressFill, progressText };
    cancelBtn.onclick = (e) => {
      var _a;
      e.stopPropagation();
      this.syncCancelled = true;
      (_a = this.currentNotice) == null ? void 0 : _a.hide();
      this.currentNotice = null;
      this.noticeContent = null;
      new import_obsidian.Notice("\u{1F6AB} Sync cancelled");
    };
    this.updateProgressDisplay();
  }
  updateProgressDisplay() {
    if (!this.noticeContent)
      return;
    const { label, progressFill, progressText } = this.noticeContent;
    const current = this.syncStats.processed;
    const total = this.syncStats.total;
    const pct = total > 0 ? Math.round(current / total * 100) : 0;
    label.textContent = `\u2B07\uFE0F ${this.syncStats.downloaded} \u23ED\uFE0F ${this.syncStats.skipped}`;
    progressFill.style.width = `${pct}%`;
    progressText.textContent = `${current}/${total}`;
  }
  async syncFromDrive() {
    var _a, _b;
    if (!this.isAuthenticated()) {
      new import_obsidian.Notice("Please sign in with Google Drive first.");
      return;
    }
    if (this.isSyncing) {
      this.showProgressNotice();
      return;
    }
    this.isSyncing = true;
    this.syncCancelled = false;
    this.syncStats = { processed: 0, downloaded: 0, skipped: 0, total: 0 };
    this.showProgressNotice();
    if (this.noticeContent) {
      this.noticeContent.label.textContent = "\u{1F504} Connecting...";
    }
    try {
      if (this.noticeContent) {
        this.noticeContent.label.textContent = `\u{1F504} Finding folder...`;
      }
      const folderId = await this.findOrCreateFolder(this.settings.driveFolderPath);
      if (this.syncCancelled) {
        this.isSyncing = false;
        return;
      }
      if (this.noticeContent) {
        this.noticeContent.label.textContent = "\u{1F504} Counting files...";
      }
      this.syncStats.total = await this.countDriveFiles(folderId);
      this.updateProgressDisplay();
      if (this.syncCancelled) {
        this.isSyncing = false;
        return;
      }
      await this.syncFolderFromDrive(folderId, "", () => {
        this.updateProgressDisplay();
      });
      if (this.syncCancelled) {
        this.isSyncing = false;
        return;
      }
      this.settings.lastSyncTime = Date.now();
      await this.saveSettings();
      (_a = this.currentNotice) == null ? void 0 : _a.hide();
      this.currentNotice = null;
      this.noticeContent = null;
      if (this.syncStats.skipped > 0) {
        new import_obsidian.Notice(`\u2705 Sync complete! ${this.syncStats.downloaded} downloaded, ${this.syncStats.skipped} skipped`);
      } else {
        new import_obsidian.Notice(`\u2705 Sync complete! ${this.syncStats.downloaded} files downloaded`);
      }
    } catch (error) {
      if (!this.syncCancelled) {
        console.error("Sync failed:", error);
        (_b = this.currentNotice) == null ? void 0 : _b.hide();
        new import_obsidian.Notice(`\u274C Sync failed: ${error.message}`);
      }
      this.currentNotice = null;
      this.noticeContent = null;
    } finally {
      this.isSyncing = false;
    }
  }
  async countDriveFiles(folderId) {
    if (this.syncCancelled)
      return 0;
    const driveFiles = await this.listDriveFiles(folderId);
    let count = 0;
    for (const file of driveFiles) {
      if (this.syncCancelled)
        return count;
      if (file.mimeType === "application/vnd.google-apps.folder") {
        count += await this.countDriveFiles(file.id);
      } else if (file.name.endsWith(".md")) {
        count++;
      }
    }
    return count;
  }
  async syncFolderFromDrive(folderId, localPath, onProgress) {
    if (this.syncCancelled)
      return;
    const driveFiles = await this.listDriveFiles(folderId);
    for (const file of driveFiles) {
      if (this.syncCancelled)
        return;
      const filePath = localPath ? `${localPath}/${file.name}` : file.name;
      if (file.mimeType === "application/vnd.google-apps.folder") {
        const folder = this.app.vault.getAbstractFileByPath(filePath);
        if (!folder) {
          try {
            await this.app.vault.createFolder(filePath);
          } catch (e) {
          }
        }
        await this.syncFolderFromDrive(file.id, filePath, onProgress);
      } else if (file.name.endsWith(".md")) {
        const cachedHash = this.settings.syncCache[filePath];
        if (cachedHash && file.md5Checksum && cachedHash === file.md5Checksum) {
          this.syncStats.processed++;
          this.syncStats.skipped++;
          if (onProgress)
            onProgress(this.syncStats.processed);
          continue;
        }
        this.syncStats.processed++;
        this.syncStats.downloaded++;
        if (onProgress)
          onProgress(this.syncStats.processed);
        const content = await this.downloadFile(file.id);
        const existingFile = this.app.vault.getAbstractFileByPath(filePath);
        if (existingFile instanceof import_obsidian.TFile) {
          await this.app.vault.modify(existingFile, content);
        } else {
          try {
            await this.app.vault.create(filePath, content);
          } catch (e) {
            const retryFile = this.app.vault.getAbstractFileByPath(filePath);
            if (retryFile instanceof import_obsidian.TFile) {
              await this.app.vault.modify(retryFile, content);
            }
          }
        }
        if (file.md5Checksum) {
          this.settings.syncCache[filePath] = file.md5Checksum;
        }
      }
    }
  }
  async syncToDrive() {
    var _a, _b, _c;
    if (!this.isAuthenticated()) {
      new import_obsidian.Notice("Please sign in with Google Drive first.");
      return;
    }
    new import_obsidian.Notice("Pushing to Google Drive...");
    try {
      const folderId = await this.findOrCreateFolder(this.settings.driveFolderPath);
      const files = this.app.vault.getMarkdownFiles();
      let uploaded = 0;
      for (const file of files) {
        const content = await this.app.vault.read(file);
        const parentPath = ((_a = file.parent) == null ? void 0 : _a.path) || "";
        const driveParentPath = parentPath ? `${this.settings.driveFolderPath}/${parentPath}` : this.settings.driveFolderPath;
        const parentFolderId = await this.findOrCreateFolder(driveParentPath);
        const query = `name='${file.name}' and '${parentFolderId}' in parents and trashed=false`;
        const existing = await this.driveRequest(
          `files?q=${encodeURIComponent(query)}&fields=files(id)`
        );
        const existingId = (_c = (_b = existing.files) == null ? void 0 : _b[0]) == null ? void 0 : _c.id;
        await this.uploadFile(file.name, content, parentFolderId, existingId);
        uploaded++;
      }
      this.settings.lastSyncTime = Date.now();
      await this.saveSettings();
      new import_obsidian.Notice(`Pushed ${uploaded} files to Google Drive!`);
    } catch (error) {
      console.error("Push failed:", error);
      new import_obsidian.Notice(`Push failed: ${error.message}`);
    }
  }
};
var VectrolaSyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
    this.authStateHandler = () => this.display();
    this.plugin.events.on("auth-state-changed", this.authStateHandler);
  }
  hide() {
    this.plugin.events.off("auth-state-changed", this.authStateHandler);
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Connection").setHeading();
    if (this.plugin.isAuthenticated()) {
      const statusBox = containerEl.createEl("div", { cls: "vectrola-status-box" });
      const statusContainer = statusBox.createEl("div", { cls: "vectrola-status-container" });
      statusContainer.createEl("span", { cls: "vectrola-status-icon", text: "\u2705" });
      const statusText = statusContainer.createEl("div", { cls: "vectrola-status-text" });
      statusText.createEl("div", { cls: "vectrola-status-title", text: "Connected to Google Drive" });
      if (this.plugin.settings.userEmail) {
        statusText.createEl("div", { cls: "vectrola-status-subtitle", text: this.plugin.settings.userEmail });
      }
      new import_obsidian.Setting(containerEl).setName("Sign out").setDesc("Disconnect from Google Drive").addButton(
        (btn) => btn.setButtonText("Sign Out").setWarning().onClick(async () => {
          await this.plugin.signOut();
          this.display();
        })
      );
    } else {
      const statusBox = containerEl.createEl("div", { cls: "vectrola-status-box" });
      const statusContainer = statusBox.createEl("div", { cls: "vectrola-status-container" });
      statusContainer.createEl("span", { cls: "vectrola-status-icon", text: "\u{1F517}" });
      const statusText = statusContainer.createEl("div", { cls: "vectrola-status-text" });
      statusText.createEl("div", { cls: "vectrola-status-title", text: "Not connected" });
      statusText.createEl("div", { cls: "vectrola-status-subtitle", text: "Sign in to sync your music wiki" });
      new import_obsidian.Setting(containerEl).setName("Sign in with Google").setDesc("Connect to Google Drive to sync your wiki").addButton(
        (btn) => btn.setButtonText("Sign in with Google").setCta().onClick(async () => {
          await this.plugin.authenticate();
          this.display();
        })
      );
    }
    new import_obsidian.Setting(containerEl).setName("Synchronization").setHeading();
    new import_obsidian.Setting(containerEl).setName("Drive folder path").setDesc("Google Drive folder where wiki is stored").addText(
      (text) => text.setPlaceholder("/Vectrola/wiki").setValue(this.plugin.settings.driveFolderPath).onChange(async (value) => {
        this.plugin.settings.driveFolderPath = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto-sync on open").setDesc("Automatically pull from Drive when vault opens").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoSyncOnOpen).onChange(async (value) => {
        this.plugin.settings.autoSyncOnOpen = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Sync interval (minutes)").setDesc("How often to sync automatically (0 to disable)").addText(
      (text) => text.setPlaceholder("5").setValue(String(this.plugin.settings.syncIntervalMinutes)).onChange(async (value) => {
        const num = parseInt(value) || 0;
        this.plugin.settings.syncIntervalMinutes = num;
        await this.plugin.saveSettings();
        this.plugin.setupSyncInterval();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Manual Sync").setHeading();
    new import_obsidian.Setting(containerEl).setName("Pull from Drive").setDesc("Download latest wiki from Google Drive").addButton(
      (btn) => btn.setButtonText("Pull").onClick(async () => {
        await this.plugin.syncFromDrive();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Push to Drive").setDesc("Upload current vault to Google Drive").addButton(
      (btn) => btn.setButtonText("Push").onClick(async () => {
        await this.plugin.syncToDrive();
      })
    );
    if (this.plugin.settings.lastSyncTime > 0) {
      const lastSync = new Date(this.plugin.settings.lastSyncTime).toLocaleString();
      containerEl.createEl("p", {
        text: `Last synced: ${lastSync}`,
        cls: "setting-item-description"
      });
    }
  }
};
